# Generated by Django 2.1.15 on 2020-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira2app', '0002_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='next_column',
            field=models.UUIDField(blank=True, default=None),
        ),
    ]
