# Generated by Django 2.1.15 on 2020-10-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jira2app', '0007_column_next_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_title', models.CharField(max_length=32)),
                ('ticket_description', models.TextField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='jira2app.Column')),
                ('notifyess', models.ManyToManyField(blank=True, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
