# Generated by Django 2.1.15 on 2020-10-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira2app', '0008_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='notifyess',
            new_name='notifyees',
        ),
    ]
