# Generated by Django 2.1.15 on 2020-10-14 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira2app', '0010_auto_20201014_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('label_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notifyees',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='labels',
            field=models.ManyToManyField(null=True, to='jira2app.Label'),
        ),
    ]
