# Generated by Django 2.1.15 on 2020-10-14 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira2app', '0011_auto_20201014_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='labels',
            field=models.ManyToManyField(blank=True, to='jira2app.Label'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notifyees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
