# Generated by Django 3.1.1 on 2020-09-09 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=32)),
                ('projectDescription', models.TextField()),
                ('isPrivate', models.BooleanField(default=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
