# -*- coding: utf-8 -*-
# Generated by Django 3.1.1 on 2020-09-09 12:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira2app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Columns",
            fields=[
                (
                    "column_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("column_name", models.CharField(max_length=32)),
                ("next_column", models.UUIDField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jira2app.projects",
                    ),
                ),
            ],
        ),
    ]
