# -*- coding: utf-8 -*-
# Generated by Django 3.1.1 on 2020-09-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jira2app", "0002_columns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects", old_name="createdTime", new_name="created_time",
        ),
        migrations.RenameField(
            model_name="projects", old_name="isPrivate", new_name="is_private",
        ),
        migrations.RenameField(
            model_name="projects", old_name="modifiedTime", new_name="modified_time",
        ),
        migrations.RenameField(
            model_name="projects",
            old_name="projectDescription",
            new_name="project_description",
        ),
        migrations.RenameField(
            model_name="projects", old_name="projectId", new_name="project_id",
        ),
        migrations.RenameField(
            model_name="projects", old_name="projectName", new_name="project_name",
        ),
    ]
