# -*- coding: utf-8 -*-
# Generated by Django 3.1.1 on 2020-09-11 10:11

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jira2app", "0003_auto_20200909_1246"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "ticket_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now=True)),
                ("modified_time", models.DateTimeField(auto_now_add=True)),
                ("ticket_description", models.TextField(null=True)),
                ("ticket_title", models.CharField(max_length=64)),
                (
                    "followers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, size=None
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jira2app.columns",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "comment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now=True)),
                ("modified_time", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jira2app.tickets",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
