# -*- coding: utf-8 -*-
# Generated by Django 3.1.1 on 2020-09-11 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jira2app", "0005_usersprojects"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="UsersProjects",
        ),
    ]
